language: node_js
node_js:
  - "10.16.3"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/test-ultra
  on:
    branch: master
