language: node_js
node_js:
  - "10.16.3"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
#   - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
#   - ng lint
  - npm run-script build
#   - ng build --prod --i18n-locale es --i18n-format xlf --i18n-file src/translate/messages.es.xlf --output-path=dist/es --baseHref /es/
  - npm run build-locale

deploy:
  edge: true
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/test-ultra
  on:
    branch: master
